# Generated by Django 5.2.7 on 2025-11-02 02:47

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rol', models.CharField(choices=[('USUARIO', 'Usuario'), ('CLIENTE', 'Cliente'), ('ADMINISTRADOR', 'Administrador'), ('CONTADOR', 'Contador'), ('VENTAS', 'Ventas'), ('SOPORTE', 'Soporte')], default='USUARIO', help_text='Rol del usuario en el sistema', max_length=20, verbose_name='Rol')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('activo', models.BooleanField(default=True, help_text='Designa si el usuario debe ser tratado como activo', verbose_name='Activo')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['-fecha_creacion'],
                'permissions': [('can_view_dashboard', 'Puede ver el dashboard'), ('can_manage_users', 'Puede gestionar usuarios'), ('can_view_reports', 'Puede ver reportes'), ('can_manage_sales', 'Puede gestionar ventas'), ('can_manage_inventory', 'Puede gestionar inventario'), ('can_manage_accounting', 'Puede gestionar contabilidad'), ('can_provide_support', 'Puede brindar soporte')],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PermisoPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del permiso')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('recurso', models.CharField(help_text='Recurso al que aplica el permiso (ej: productos, ventas, etc.)', max_length=100, verbose_name='Recurso')),
                ('puede_crear', models.BooleanField(default=False, verbose_name='Puede crear')),
                ('puede_leer', models.BooleanField(default=False, verbose_name='Puede leer')),
                ('puede_actualizar', models.BooleanField(default=False, verbose_name='Puede actualizar')),
                ('puede_eliminar', models.BooleanField(default=False, verbose_name='Puede eliminar')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos_personalizados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Permiso Personalizado',
                'verbose_name_plural': 'Permisos Personalizados',
                'unique_together': {('usuario', 'recurso', 'nombre')},
            },
        ),
    ]
