# Generated by Django 5.1.4 on 2025-11-02 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-fecha_creacion'], 'permissions': [('can_view_dashboard', 'Puede ver el dashboard'), ('can_manage_users', 'Puede gestionar usuarios'), ('can_view_reports', 'Puede ver reportes'), ('can_manage_sales', 'Puede gestionar ventas'), ('can_manage_inventory', 'Puede gestionar inventario'), ('can_manage_accounting', 'Puede gestionar contabilidad'), ('can_provide_support', 'Puede brindar soporte'), ('can_manage_caja', 'Puede abrir/cerrar caja'), ('can_view_caja', 'Puede ver movimientos de caja')], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
    ]
