# Generated by Django 5.1.4 on 2025-11-03 04:54

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_factura', models.CharField(help_text='Formato: FACT-000001', max_length=50, unique=True, verbose_name='Código de Factura')),
                ('fecha_emision', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Emisión')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Subtotal')),
                ('total_descuentos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total Descuentos')),
                ('subtotal_neto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Subtotal Neto')),
                ('total_iva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total IVA (19%)')),
                ('total_pagar', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total a Pagar')),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia Bancaria'), ('TARJETA', 'Tarjeta de Crédito/Débito'), ('CHEQUE', 'Cheque'), ('OTRO', 'Otro')], default='EFECTIVO', max_length=20, verbose_name='Método de Pago')),
                ('condicion_pago', models.CharField(choices=[('CONTADO', 'Contado (Pago Inmediato)'), ('CREDITO_15', 'Crédito 15 Días'), ('CREDITO_30', 'Crédito 30 Días'), ('CREDITO_60', 'Crédito 60 Días'), ('CREDITO_90', 'Crédito 90 Días')], default='CONTADO', max_length=20, verbose_name='Condición de Pago')),
                ('notas', models.TextField(blank=True, help_text='Condiciones, garantías, agradecimientos, etc.', null=True, verbose_name='Notas')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('activa', models.BooleanField(default=True, help_text='Indica si la factura está activa o fue anulada', verbose_name='Activa')),
                ('cliente', models.ForeignKey(limit_choices_to={'rol': 'CLIENTE'}, on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('usuario_emisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas_emitidas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Emisor')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(help_text='Nombre o descripción del producto/servicio', max_length=500, verbose_name='Descripción')),
                ('cantidad', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10, verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, help_text='Precio sin impuestos', max_digits=12, verbose_name='Precio Unitario')),
                ('descuento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Descuento en pesos', max_digits=12, verbose_name='Descuento')),
                ('valor_unitario', models.DecimalField(decimal_places=2, help_text='Precio unitario después del descuento', max_digits=12, verbose_name='Valor Unitario')),
                ('total', models.DecimalField(decimal_places=2, help_text='Valor unitario × Cantidad', max_digits=12, verbose_name='Total')),
                ('producto_oscar_id', models.IntegerField(blank=True, help_text='ID del producto en el catálogo Oscar', null=True, verbose_name='ID Producto Oscar')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='facturacion.factura', verbose_name='Factura')),
            ],
            options={
                'verbose_name': 'Detalle de Factura',
                'verbose_name_plural': 'Detalles de Factura',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['-fecha_emision'], name='facturacion_fecha_e_409ab1_idx'),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['codigo_factura'], name='facturacion_codigo__d41175_idx'),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['cliente'], name='facturacion_cliente_1abe53_idx'),
        ),
    ]
