# Generated by Django 5.1.4 on 2025-11-02 05:18

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DenominacionMoneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, unique=True, verbose_name='Valor')),
                ('tipo', models.CharField(choices=[('BILLETE', 'Billete'), ('MONEDA', 'Moneda')], max_length=10, verbose_name='Tipo')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de aparición (menor número aparece primero)', verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Denominación de Moneda',
                'verbose_name_plural': 'Denominaciones de Monedas',
                'ordering': ['-valor'],
            },
        ),
        migrations.CreateModel(
            name='TipoMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Tipo de Movimiento',
                'verbose_name_plural': 'Tipos de Movimientos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CajaRegistradora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de apertura')),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de cierre')),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('CERRADA', 'Cerrada')], default='ABIERTA', max_length=10, verbose_name='Estado')),
                ('monto_inicial', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Dinero en efectivo al abrir la caja', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Monto inicial')),
                ('monto_final_declarado', models.DecimalField(blank=True, decimal_places=2, help_text='Dinero contado al cerrar la caja', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Monto final declarado')),
                ('monto_final_sistema', models.DecimalField(blank=True, decimal_places=2, help_text='Monto calculado por el sistema', max_digits=12, null=True, verbose_name='Monto final sistema')),
                ('diferencia', models.DecimalField(blank=True, decimal_places=2, help_text='Diferencia entre declarado y sistema', max_digits=12, null=True, verbose_name='Diferencia')),
                ('observaciones_apertura', models.TextField(blank=True, verbose_name='Observaciones de apertura')),
                ('observaciones_cierre', models.TextField(blank=True, verbose_name='Observaciones de cierre')),
                ('cajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cajas_manejadas', to=settings.AUTH_USER_MODEL, verbose_name='Cajero')),
            ],
            options={
                'verbose_name': 'Caja Registradora',
                'verbose_name_plural': 'Cajas Registradoras',
                'ordering': ['-fecha_apertura'],
            },
        ),
        migrations.CreateModel(
            name='ConteoEfectivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_conteo', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de conteo')),
                ('total_contado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total contado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('caja', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conteo_efectivo', to='caja.cajaregistradora', verbose_name='Caja')),
            ],
            options={
                'verbose_name': 'Conteo de Efectivo',
                'verbose_name_plural': 'Conteos de Efectivo',
            },
        ),
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso'), ('EGRESO', 'Egreso')], max_length=10, verbose_name='Tipo')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto')),
                ('descripcion', models.TextField(help_text='Detalle del movimiento', verbose_name='Descripción')),
                ('referencia', models.CharField(blank=True, help_text='Número de factura, recibo, etc.', max_length=100, verbose_name='Referencia')),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del movimiento')),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='caja.cajaregistradora', verbose_name='Caja')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('tipo_movimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caja.tipomovimiento', verbose_name='Tipo de movimiento')),
            ],
            options={
                'verbose_name': 'Movimiento de Caja',
                'verbose_name_plural': 'Movimientos de Caja',
                'ordering': ['-fecha_movimiento'],
            },
        ),
        migrations.CreateModel(
            name='DetalleConteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0, verbose_name='Cantidad')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Subtotal')),
                ('conteo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='caja.conteoefectivo', verbose_name='Conteo')),
                ('denominacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caja.denominacionmoneda', verbose_name='Denominación')),
            ],
            options={
                'verbose_name': 'Detalle de Conteo',
                'verbose_name_plural': 'Detalles de Conteo',
                'unique_together': {('conteo', 'denominacion')},
            },
        ),
    ]
