# Generated by Django 5.1.4 on 2025-11-02 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conteoefectivo',
            options={'ordering': ['-fecha_conteo'], 'verbose_name': 'Conteo de Efectivo', 'verbose_name_plural': 'Conteos de Efectivo'},
        ),
        migrations.RenameField(
            model_name='conteoefectivo',
            old_name='total_contado',
            new_name='total',
        ),
        migrations.AddField(
            model_name='conteoefectivo',
            name='tipo_conteo',
            field=models.CharField(choices=[('APERTURA', 'Apertura'), ('CIERRE', 'Cierre')], default='CIERRE', max_length=10, verbose_name='Tipo de conteo'),
        ),
        migrations.AddField(
            model_name='conteoefectivo',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que realizó el conteo'),
        ),
        migrations.AlterField(
            model_name='conteoefectivo',
            name='caja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conteos', to='caja.cajaregistradora', verbose_name='Caja'),
        ),
    ]
