# Generated by Django 5.1.4 on 2025-11-02 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0002_cambio_conteo_a_fk_y_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientocaja',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Detalle del movimiento (opcional)', verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='movimientocaja',
            name='referencia',
            field=models.CharField(blank=True, help_text='Número de factura, recibo, etc. (opcional)', max_length=100, verbose_name='Referencia'),
        ),
    ]
