# Generated by Django 5.1.4 on 2025-11-02 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0003_alter_movimientocaja_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denominacionmoneda',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor'),
        ),
        migrations.AlterUniqueTogether(
            name='denominacionmoneda',
            unique_together={('valor', 'tipo')},
        ),
    ]
