# Generated by Django 5.1.4 on 2025-11-02 17:18

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0004_alter_denominacionmoneda_valor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cajaregistradora',
            name='dinero_en_caja',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Dinero que quedó en la caja al cerrar', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Dinero en caja'),
        ),
        migrations.AddField(
            model_name='cajaregistradora',
            name='dinero_guardado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Dinero guardado fuera de la caja al cerrar', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Dinero guardado'),
        ),
    ]
