# Generated by Django 5.1.4 on 2025-11-07 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0005_cajaregistradora_dinero_en_caja_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipomovimiento',
            name='codigo',
            field=models.CharField(max_length=20, unique=True, verbose_name='Código'),
        ),
    ]
