# Generated by Django 5.1.4 on 2025-11-07 04:55

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0007_create_default_tipos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la cuenta')),
                ('tipo', models.CharField(choices=[('BANCO', 'Banco'), ('RESERVA', 'Reserva / Dinero Guardado')], max_length=20, verbose_name='Tipo de cuenta')),
                ('saldo_actual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Saldo disponible en esta cuenta', max_digits=12, verbose_name='Saldo actual')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Cuenta',
                'verbose_name_plural': 'Cuentas',
                'ordering': ['tipo', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='tipomovimiento',
            name='tipo_base',
            field=models.CharField(choices=[('INGRESO', 'Ingreso'), ('GASTO', 'Gasto Operativo'), ('INVERSION', 'Compra / Inversión'), ('INTERNO', 'Movimiento Interno')], default='GASTO', help_text='Categoría base para filtrado en tesorería', max_length=20, verbose_name='Tipo Base'),
        ),
        migrations.CreateModel(
            name='TransaccionGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de transacción')),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso'), ('EGRESO', 'Egreso'), ('TRANSFERENCIA', 'Transferencia')], max_length=20, verbose_name='Tipo de transacción')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('referencia', models.CharField(blank=True, help_text='Número de comprobante, recibo, etc.', max_length=100, verbose_name='Referencia')),
                ('cuenta', models.ForeignKey(help_text='Cuenta de origen (para egresos) o destino (para ingresos)', on_delete=django.db.models.deletion.PROTECT, related_name='transacciones', to='caja.cuenta', verbose_name='Cuenta')),
                ('cuenta_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_recibidas', to='caja.cuenta', verbose_name='Cuenta destino')),
                ('movimiento_caja_asociado', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='caja.movimientocaja', verbose_name='Movimiento de caja asociado')),
                ('tipo_movimiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='caja.tipomovimiento', verbose_name='Tipo de movimiento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Transacción General',
                'verbose_name_plural': 'Transacciones Generales',
                'ordering': ['-fecha'],
            },
        ),
    ]
