# Generated by Django 5.1.4 on 2025-11-07 04:55

from django.db import migrations


def asignar_tipo_base(apps, schema_editor):
    """
    Asigna el tipo_base correcto a los 13 tipos de movimiento existentes.
    """
    TipoMovimiento = apps.get_model('caja', 'TipoMovimiento')
    
    # INGRESO
    tipos_ingreso = ['VENTA', 'COBRO_CXC', 'DEV_PAGO', 'REC_GASTOS']
    TipoMovimiento.objects.filter(codigo__in=tipos_ingreso).update(tipo_base='INGRESO')
    
    # GASTO (Gastos operativos)
    tipos_gasto = ['GASTO', 'SUELDOS', 'SUMINISTROS', 'ALQUILER', 'MANTENIMIENTO', 'DEV_VENTA']
    TipoMovimiento.objects.filter(codigo__in=tipos_gasto).update(tipo_base='GASTO')
    
    # INVERSION (Compras e inversiones)
    tipos_inversion = ['COMPRA', 'FLETES']
    TipoMovimiento.objects.filter(codigo__in=tipos_inversion).update(tipo_base='INVERSION')
    
    # INTERNO (Movimientos internos)
    tipos_interno = ['APERTURA']
    TipoMovimiento.objects.filter(codigo__in=tipos_interno).update(tipo_base='INTERNO')


def revertir_tipo_base(apps, schema_editor):
    """Revertir al valor por defecto."""
    TipoMovimiento = apps.get_model('caja', 'TipoMovimiento')
    TipoMovimiento.objects.all().update(tipo_base='GASTO')


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0008_cuenta_tipomovimiento_tipo_base_transacciongeneral'),
    ]

    operations = [
        migrations.RunPython(asignar_tipo_base, revertir_tipo_base),
    ]
