# Generated by Django 5.1.4 on 2025-11-07 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0009_asignar_tipo_base_tipos'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientocaja',
            name='transaccion_asociada',
            field=models.OneToOneField(blank=True, help_text='Transacción de tesorería generada por este movimiento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimiento_caja_origen', to='caja.transacciongeneral', verbose_name='Transacción asociada'),
        ),
    ]
